### ISSUE TITLE
Update to support w.org language translations

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/edd-featured-downloads#9]
See details [here](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/). If we ditch `load_plugin_textdomain()`, add the domain and path to the header, change the domain to match the slug and require WP 4.6 or higher we can let community translations on w.org work instead of shipping them ourselves.

This would nullify #8

**Comment by amdrew** [comment]
Pretty sure I've done all that's required to allow for automatic translations on .org. 

1. Updated the "Requires at least" readme header to 4.6
2. Removed the function that loads `load_plugin_textdomain()`
3. Renamed the current text domain so it matches the plugin slug
4. Removed the current languages. I think these are already imported and are no longer required since all translation happen on .org.

From what I've read, the text domain and domain path are not required in the plugin header:

> After WordPress 4.6 came out, the Text Domain header is no longer required if it’s the same as the plugin slug. It’s now the default value.

https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#text-domains

> The Domain Path header can be omitted if the plugin is in the official WordPress Plugin Directory.

https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#domain-path

With that, I'm going to close this issue and push out the `1.0.4` update.

**Comment by pippinsplugins** [comment]
@amdrew yep looks right!

**Comment by amdrew** [comment]
Ok coolio, I'll get the update out soon.

**Comment by amdrew** [comment]
An update on this/some notes for the future automatic translations:

After updating the plugin I checked the translation page and saw this notice:

<img width="1006" alt="screen shot 2018-08-31 at 12 20 02 pm" src="https://user-images.githubusercontent.com/52581/44886481-734d4980-ad1a-11e8-8c04-d71861bc518e.png">

After clicking the notice there's some information on another page:

> “This plugin is not properly prepared for localization.” – Help? #“This plugin is not properly prepared for localization.” – Help?

> You get this message on your plugin page at translate.wordpress.org and it usually means that something is wrong with the text domain. To get the details about a failed import please join the Slack team and switch to the #meta-language-packs channel. All imports are getting logged here. Search by the slug of your plugin to get the relevant results.

I logged into the slack channel and ran the search as suggested but there was nothing recent for the `edd-featured-downloads` slug (not since 2017).

It turns out the text domain header is still needed (even though the docs said it wasn't). After adding that and committing the slack channel updated:

<img width="587" alt="screen shot 2018-08-31 at 12 35 17 pm" src="https://user-images.githubusercontent.com/52581/44886549-f5d60900-ad1a-11e8-8385-1a53687b4694.png">

And the notice on the plugin page is now gone:

<img width="986" alt="screen shot 2018-08-31 at 12 40 27 pm" src="https://user-images.githubusercontent.com/52581/44886562-1736f500-ad1b-11e8-83b1-8c7170c41f06.png">

🎉
